# Generated by Django 5.1.4 on 2026-08-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0009_alter_discoveredboard_ats_alter_jobsource_ats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoApplyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('stale', 'Stale'), ('sending', 'Sending'), ('applied', 'Applied'), ('failed', 'Failed'), ('excluded', 'Excluded')], default='drafted', max_length=16)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Resolved per-question answer set, including confidence/needs_review metadata.')),
                ('answers_schema_version', models.IntegerField(default=1)),
                ('exclusion_reason', models.TextField(blank=True, help_text='Populated when status=EXCLUDED (R6).', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Populated when status=FAILED (R14).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_apply_drafts', to='jobs.job')),
                ('job_application', models.ForeignKey(blank=True, help_text="Set only once a send succeeds and links to the real JobApplication record; PROTECT so a completed auto-apply's link to its submission never silently cascade-deletes.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_apply_drafts', to='applications.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_apply_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['drafted', 'sending'])), fields=('user', 'job'), name='uniq_autoapplydraft_user_job_active')],
            },
        ),
        migrations.CreateModel(
            name='ExplicitAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('work_authorization', 'Work authorization'), ('sponsorship', 'Sponsorship'), ('salary_expectation', 'Salary expectation'), ('other', 'Other')], max_length=32)),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicit_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='uniq_explicitanswer_user_category')],
            },
        ),
    ]
