# Generated by Django 5.1.4 on 2026-08-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapplydraft',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('schema_mismatch', 'Unsupported form field'), ('form_load_failed', 'Could not load application form'), ('unanswerable_required', 'Required question unanswered'), ('captcha_challenged', 'Bot-detection challenge'), ('submission_failed', 'Submission rejected'), ('sending_timeout', 'Submission timed out'), ('unexpected_error', 'Unexpected error')], help_text='Machine-readable reason for EXCLUDED/FAILED, set alongside exclusion_reason/error_message. UI code should switch on this, not the free-text message.', max_length=32, null=True),
        ),
    ]
