# Generated by Django 5.1.4 on 2026-08-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_apply', '0002_autoapplydraft_reason_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapplydraft',
            name='form_schema_snapshot',
            field=models.JSONField(blank=True, help_text='The Greenhouse application-page FormSchema (see apps.auto_apply.greenhouse_form.field_mapping) captured at draft time. Passed back to GreenhouseFormClient.submit() as expected_schema at send time so the schema-drift check can actually run -- without this, drift detection has no baseline to compare the live page against.', null=True),
        ),
    ]
