# Generated by Django 5.1.4 on 2026-09-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('auto_apply', '0003_autoapplydraft_form_schema_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapplydraft',
            name='job_application',
            field=models.ForeignKey(blank=True, help_text="Set only once a send succeeds and links to the real JobApplication record; RESTRICT so a completed auto-apply's link to its submission never silently cascade-deletes.", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='auto_apply_drafts', to='applications.jobapplication'),
        ),
        migrations.AlterField(
            model_name='autoapplydraft',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('schema_mismatch', 'Unsupported form field'), ('form_load_failed', 'Could not load application form'), ('unanswerable_required', 'Required question unanswered'), ('captcha_challenged', 'Bot-detection challenge'), ('submission_failed', 'Submission rejected'), ('submission_unconfirmed', 'Submission not confirmed'), ('sending_timeout', 'Submission timed out'), ('unexpected_error', 'Unexpected error')], help_text='Machine-readable reason for EXCLUDED/FAILED, set alongside exclusion_reason/error_message. UI code should switch on this, not the free-text message.', max_length=32, null=True),
        ),
    ]
