# Generated by Django 5.1.4 on 2026-09-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('auto_apply', '0004_alter_autoapplydraft_reason_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapplydraft',
            name='job_application',
            field=models.ForeignKey(blank=True, help_text='Set only once a send succeeds and links to the real JobApplication record; RESTRICT (not PROTECT) so a direct JobApplication delete is still refused, while deleting the owning User or Job -- which cascades to both rows -- still works.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='auto_apply_drafts', to='applications.jobapplication'),
        ),
    ]
