# Generated by Django 5.1.4 on 2026-09-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_apply', '0004_alter_autoapplydraft_job_application_and_more'),
        ('auto_apply', '0004_alter_autoapplydraft_reason_code'),
    ]

    operations = [
    ]
