# Generated by Django 5.1.4 on 2026-09-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_apply', '0005_autoapplydraft_job_application_restrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapplydraft',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('schema_mismatch', 'Unsupported form field'), ('form_load_failed', 'Could not load application form'), ('unanswerable_required', 'Required question unanswered'), ('captcha_challenged', 'Bot-detection challenge'), ('submission_failed', 'Submission rejected'), ('submission_unconfirmed', 'Submission not confirmed'), ('sending_timeout', 'Submission timed out'), ('unexpected_error', 'Unexpected error'), ('no_inbox_credentials', 'No inbox credentials connected'), ('verification_code_timeout', 'Verification email timed out'), ('inbox_auth_failed', 'Inbox authentication failed'), ('inbox_unavailable', 'Inbox connection unavailable'), ('verification_code_ambiguous', 'Multiple verification codes found'), ('verification_code_rejected', 'Verification code rejected')], help_text='Machine-readable reason for EXCLUDED/FAILED, set alongside exclusion_reason/error_message. UI code should switch on this, not the free-text message.', max_length=32, null=True),
        ),
    ]
