# Generated by Django 5.1.4 on 2026-09-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_apply', '0006_alter_autoapplydraft_reason_code'),
        ('auto_apply', '0007_autoapplydraft_reason_code_verification_busy'),
    ]

    operations = [
    ]
