# Generated by Django 5.1.4 on 2026-09-30 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('auto_apply', '0008_merge_20260930_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapplydraft',
            name='job_application',
            field=models.ForeignKey(blank=True, help_text='Set only once a send succeeds and links to the real JobApplication record; RESTRICT (not PROTECT) so a direct JobApplication delete is still refused, while deleting the owning User or Job -- which cascades to both rows -- still works.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='auto_apply_drafts', to='applications.jobapplication'),
        ),
        migrations.AlterField(
            model_name='autoapplydraft',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('schema_mismatch', 'Unsupported form field'), ('form_load_failed', 'Could not load application form'), ('unanswerable_required', 'Required question unanswered'), ('captcha_challenged', 'Bot-detection challenge'), ('submission_failed', 'Submission rejected'), ('submission_unconfirmed', 'Submission not confirmed'), ('sending_timeout', 'Submission timed out'), ('unexpected_error', 'Unexpected error'), ('no_inbox_credentials', 'No inbox credentials connected'), ('verification_code_timeout', 'Verification email timed out'), ('inbox_auth_failed', 'Inbox authentication failed'), ('inbox_unavailable', 'Inbox connection unavailable'), ('verification_code_ambiguous', 'Multiple verification codes found'), ('verification_busy', 'Another verification in progress'), ('verification_code_rejected', 'Verification code rejected'), ('resume_replaced', 'Resume was replaced')], help_text='Machine-readable reason for EXCLUDED/FAILED, set alongside exclusion_reason/error_message. UI code should switch on this, not the free-text message.', max_length=32, null=True),
        ),
    ]
