# Generated by Django 5.1.4 on 2026-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_apply', '0009_alter_autoapplydraft_job_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapplydraft',
            name='submitted_answers_snapshot',
            field=models.JSONField(blank=True, help_text='Write-once record of the exact answers and their provenance at the moment the draft moved to SENDING (legal-attestation audit trail). See apps.auto_apply.services.confirmation.', null=True),
        ),
        migrations.AlterField(
            model_name='autoapplydraft',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('schema_mismatch', 'Unsupported form field'), ('form_load_failed', 'Could not load application form'), ('unanswerable_required', 'Required question unanswered'), ('captcha_challenged', 'Bot-detection challenge'), ('submission_failed', 'Submission rejected'), ('submission_unconfirmed', 'Submission not confirmed'), ('sending_timeout', 'Submission timed out'), ('unexpected_error', 'Unexpected error'), ('no_inbox_credentials', 'No inbox credentials connected'), ('verification_code_timeout', 'Verification email timed out'), ('inbox_auth_failed', 'Inbox authentication failed'), ('inbox_unavailable', 'Inbox connection unavailable'), ('verification_code_ambiguous', 'Multiple verification codes found'), ('verification_busy', 'Another verification in progress'), ('verification_code_rejected', 'Verification code rejected'), ('resume_replaced', 'Resume was replaced'), ('unconfirmed_answers', 'Answers awaiting your confirmation')], help_text='Machine-readable reason for EXCLUDED/FAILED, set alongside exclusion_reason/error_message. UI code should switch on this, not the free-text message.', max_length=32, null=True),
        ),
    ]
