# Generated by Django 5.1.4 on 2026-07-17 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('headline', models.CharField(blank=True, default='', max_length=255)),
                ('target_titles', models.JSONField(blank=True, default=list)),
                ('target_tags', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('excluded_employers', models.JSONField(blank=True, default=list, help_text='Employer slugs to exclude from recommendations.')),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('remote_pref', models.CharField(choices=[('any', 'Any'), ('remote_only', 'Remote only'), ('onsite_only', 'On-site only')], default='any', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
