# Generated by Django 5.1.4 on 2026-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_locations_alias_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_locations_normalized',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
