# Generated by Django 5.1.4 on 2026-08-02 17:22

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_profile_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF/DOCX/TXT only. Parsed into resume_text asynchronously.', null=True, upload_to=apps.accounts.models.resume_upload_path, validators=[apps.accounts.models.validate_resume_file]),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
