# Generated by Django 5.1.4 on 2026-08-04 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_add_resume_and_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInboxCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('app_password_encrypted', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=32)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_inbox_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
