# Generated by Django 5.1.4 on 2026-09-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailinboxcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_employer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
