# Generated by Django 5.1.4 on 2026-10-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_current_employer_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('CAD', 'CAD (C$)'), ('AUD', 'AUD (A$)'), ('INR', 'INR (₹)'), ('SGD', 'SGD (S$)'), ('CHF', 'CHF'), ('JPY', 'JPY (¥)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_by_region',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='visa_status',
            field=models.CharField(blank=True, choices=[('citizen', 'Citizen'), ('permanent_resident', 'Permanent resident (Green card)'), ('h1b', 'H-1B'), ('opt', 'OPT (F-1 OPT)'), ('cpt', 'CPT (F-1 CPT)'), ('o1', 'O-1'), ('tn', 'TN (NAFTA)'), ('e3', 'E-3 (Australian)'), ('other', 'Other visa status'), ('not_authorized', 'Not authorized')], default='', max_length=32),
        ),
    ]
