# Generated by Django 5.1.4 on 2026-10-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_per_country_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AnswerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=255)),
                ('question_text', models.TextField(blank=True, default='')),
                ('value', models.JSONField()),
                ('category', models.CharField(choices=[('experience', 'Experience'), ('technologies', 'Technologies'), ('relocation', 'Relocation'), ('projects', 'Projects'), ('education', 'Education'), ('availability', 'Availability'), ('compliance', 'Compliance'), ('other', 'Other')], default='other', max_length=32)),
                ('risk_tier', models.CharField(choices=[('t0_legal', 'T0 - legal attestation'), ('t1_commercial', 'T1 - commercial'), ('t2_factual', 'T2 - factual')], max_length=16)),
                ('source', models.CharField(choices=[('user', 'User'), ('learned', 'Learned'), ('imported', 'Imported')], max_length=16)),
                ('source_detail', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('is_locked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_bank', to='accounts.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'question_key'), name='uniq_answerbank_profile_question_key'), models.CheckConstraint(condition=models.Q(('is_locked', True), ('source__in', ['learned', 'imported']), _negated=True), name='chk_answerbank_locked_only_user')],
            },
        ),
        migrations.CreateModel(
            name='AnswerBankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('risk_tier', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=16)),
                ('source_detail', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('was_locked', models.BooleanField(default=False)),
                ('superseded_by_source', models.CharField(blank=True, default='', max_length=16)),
                ('superseded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_bank_history', to='accounts.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'question_key'], name='abh_profile_question_idx')],
            },
        ),
    ]
