# Generated by Django 5.1.4 on 2026-10-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_answerbank_field_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_country',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
