# Generated by Django 5.1.4 on 2026-10-04 11:09

import re

import django.db.models.deletion
from django.db import migrations, models

# Phase 1 keys ended in "#<10 hex>", a hash of the option set. The key is now
# the question text only (options are mapped onto the live form at resolve
# time), so strip the suffix and keep one row per resulting key.
_OPTIONS_SUFFIX = re.compile(r"#[0-9a-f]{10}$")
_SOURCE_RANK = {"imported": 1, "learned": 2, "user": 3}


def _rank(row):
    return (4 if row.is_locked else _SOURCE_RANK.get(row.source, 0), row.updated_at)


def strip_options_hash_from_keys(apps, schema_editor):
    AnswerBank = apps.get_model("accounts", "AnswerBank")
    History = apps.get_model("accounts", "AnswerBankHistory")

    # Group rows by (profile, stripped key); keep the highest-precedence one
    # (newest wins a tie) and record the others in history before dropping
    # them, so no answer the user gave silently disappears.
    groups = {}
    for row in AnswerBank.objects.all().iterator():
        groups.setdefault((row.profile_id, _OPTIONS_SUFFIX.sub("", row.question_key)), []).append(row)
    for (_profile_id, key), rows in groups.items():
        rows.sort(key=_rank, reverse=True)
        keeper, losers = rows[0], rows[1:]
        for loser in losers:
            History.objects.create(
                profile_id=loser.profile_id,
                question_key=key,
                value=loser.value,
                risk_tier=loser.risk_tier,
                source=loser.source,
                source_detail=loser.source_detail,
                confidence=loser.confidence,
                was_locked=loser.is_locked,
                superseded_by_source="migration",
            )
            loser.delete()
        if keeper.question_key != key:
            keeper.question_key = key
            keeper.save(update_fields=["question_key"])

    for entry in History.objects.filter(question_key__contains="#").iterator():
        stripped = _OPTIONS_SUFFIX.sub("", entry.question_key)
        if stripped != entry.question_key:
            History.objects.filter(pk=entry.pk).update(question_key=stripped)


def noop_reverse(apps, schema_editor):
    """Option hashes cannot be reconstructed; the shorter key is still valid."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_location_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=255)),
                ('question_text', models.TextField(blank=True, default='')),
                ('value', models.JSONField()),
                ('tier', models.CharField(max_length=16)),
                ('field_type', models.CharField(blank=True, default='', max_length=32)),
                ('provenance_source', models.CharField(blank=True, default='', max_length=16)),
                ('provenance_origin', models.CharField(blank=True, default='', max_length=64)),
                ('was_edited', models.BooleanField(default=False)),
                ('job_id', models.BigIntegerField(blank=True, null=True)),
                ('draft_id', models.BigIntegerField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, default='', max_length=255)),
                ('job_region', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='answerbank',
            name='uniq_answerbank_profile_question_key',
        ),
        migrations.AddField(
            model_name='answerbank',
            name='scope_region',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='answerbankhistory',
            name='scope_region',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.RunPython(strip_options_hash_from_keys, noop_reverse),
        migrations.AddConstraint(
            model_name='answerbank',
            constraint=models.UniqueConstraint(fields=('profile', 'question_key', 'scope_region'), name='uniq_answerbank_profile_question_key_scope'),
        ),
        migrations.AddField(
            model_name='answerobservation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_observations', to='accounts.profile'),
        ),
        migrations.AddIndex(
            model_name='answerobservation',
            index=models.Index(fields=['profile', 'question_key'], name='aobs_profile_question_idx'),
        ),
    ]
