# Generated by Django 5.1.4 on 2026-10-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_answerbank_scope_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerobservation',
            old_name='was_edited',
            new_name='user_confirmed',
        ),
        migrations.AddField(
            model_name='answerobservation',
            name='learned_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerobservation',
            name='remember_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerobservation',
            name='user_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProfileSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=255)),
                ('scope_region', models.CharField(blank=True, default='', max_length=8)),
                ('question_text', models.TextField(blank=True, default='')),
                ('value', models.JSONField()),
                ('value_fingerprint', models.CharField(max_length=40)),
                ('tier', models.CharField(max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('learner_version', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounts.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'status'], name='psugg_profile_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'question_key', 'scope_region', 'value_fingerprint'), name='uniq_profilesuggestion_profile_key_scope_value')],
            },
        ),
    ]
