# Generated by Django 5.1.4 on 2026-10-05 10:03

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_learning_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='llm_import_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='llm_import_consent_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('document', 'Document'), ('github', 'GitHub')], max_length=16)),
                ('source_kind', models.CharField(choices=[('resume', 'Resume upload'), ('linkedin_pdf', 'LinkedIn PDF'), ('current_resume', 'Saved resume'), ('github', 'GitHub')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready for review'), ('applied', 'Applied'), ('discarded', 'Discarded'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('extractor', models.CharField(choices=[('rule', 'Rules'), ('llm', 'LLM')], default='rule', max_length=8)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('source_file', models.FileField(blank=True, null=True, upload_to=apps.accounts.models.import_upload_path)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.default_import_expiry)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='importjob_status_exp_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('profile',), name='uniq_importjob_one_inflight_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='ResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('experience', 'Experience'), ('project', 'Project')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('precision', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=8)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('imported', 'Imported'), ('user', 'User')], default='imported', max_length=16)),
                ('natural_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_entries', to='accounts.profile')),
            ],
            options={
                'ordering': ['-is_current', '-start_date', 'title'],
                'indexes': [models.Index(fields=['profile', 'kind'], name='resumeentry_profile_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'kind', 'natural_key'), name='uniq_resumeentry_profile_kind_key')],
            },
        ),
    ]
