# Generated by Django 5.1.4 on 2026-10-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_import_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeentry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resumeentry',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=40)),
                ('origin', models.CharField(choices=[('github', 'GitHub')], max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='accounts.profile')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'key'), name='uniq_profileskill_profile_key')],
            },
        ),
    ]
