# Generated by Django 5.1.4 on 2026-07-17 18:52

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        # Enable the pgvector extension before creating the VectorField column.
        VectorExtension(),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ats', models.CharField(max_length=32)),
                ('source_job_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('classification_tags', models.JSONField(blank=True, default=list)),
                ('ruleset_version', models.CharField(blank=True, default='', max_length=32)),
                ('needs_classification', models.BooleanField(default=True)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='employers.employer')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['classification_tags'], name='job_tags_gin'), models.Index(fields=['status'], name='job_status_idx'), models.Index(fields=['is_remote'], name='job_is_remote_idx'), models.Index(fields=['location'], name='job_location_idx'), models.Index(fields=['needs_classification'], name='job_needs_class_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_ats', 'source_job_id'), name='uniq_job_source_ats_source_job_id')],
            },
        ),
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats', models.CharField(choices=[('greenhouse', 'Greenhouse')], default='greenhouse', max_length=32)),
                ('board_token', models.CharField(help_text='ATS board identifier (e.g. Greenhouse board token).', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the hourly ingestion sweep pulls from this board.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sources', to='employers.employer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ats', 'board_token'), name='uniq_jobsource_ats_board_token')],
            },
        ),
    ]
