# Generated by Django 5.1.4 on 2026-07-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
