# Generated by Django 5.1.4 on 2026-07-18 08:00
#
# jobs_job receives hourly writes from the ingestion pipeline
# (apps.jobs.tasks.ingest_all_active_sources), so this index is built
# CONCURRENTLY to avoid taking an ACCESS EXCLUSIVE lock on a hot table.
# atomic = False is required for AddIndexConcurrently — CREATE INDEX
# CONCURRENTLY cannot run inside a transaction.
#
# Post-deploy verification:
#   SELECT indexrelid::regclass, indisvalid
#   FROM pg_index WHERE indexrelid = 'job_search_gin'::regclass;
#   -- indisvalid must be true. If false, the CONCURRENTLY build failed
#   -- partway through and left an unusable index.
#
# Rollback if left INVALID:
#   DROP INDEX CONCURRENTLY IF EXISTS job_search_gin;
#   -- then re-run this migration.

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('employers', '0001_initial'),
        ('jobs', '0002_job_source_url'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'description', config='english'), name='job_search_gin'),
        ),
    ]
