# Generated by Django 5.1.4 on 2026-07-18 08:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('jobs', '0002_job_source_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'description', config='english'), name='job_search_gin'),
        ),
    ]
