# Generated by Django 5.1.4 on 2026-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_search_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats', models.CharField(choices=[('greenhouse', 'Greenhouse')], default='greenhouse', max_length=32)),
                ('board_token', models.CharField(help_text='ATS board identifier extracted from the discovery search result.', max_length=255)),
                ('source_url', models.URLField(blank=True, default='', help_text='Where this candidate was found (the search result URL).', max_length=1024)),
                ('derived_employer_name', models.CharField(max_length=255)),
                ('discovered_job_count', models.IntegerField(default=0, help_text='Open job count seen at discovery-time validation — compared against the approval-time re-fetch to flag a board that changed materially between discovery and review.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ats', 'board_token'), name='uniq_discoveredboard_ats_board_token')],
            },
        ),
    ]
