# Generated by Django 5.1.4 on 2026-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('jobs', '0004_discoveredboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_alias_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='location_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location_country',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location_region',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location_resolved'], name='job_location_resolved_idx'),
        ),
    ]
