# Generated by Django 5.1.4 on 2026-07-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_backfill_job_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredboard',
            name='ats',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby')], default='greenhouse', max_length=32),
        ),
        migrations.AlterField(
            model_name='jobsource',
            name='ats',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby')], default='greenhouse', max_length=32),
        ),
    ]
