# Generated by Django 5.1.4 on 2026-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_discoveredboard_ats_alter_jobsource_ats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredboard',
            name='ats',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('workday', 'Workday')], default='greenhouse', max_length=32),
        ),
        migrations.AlterField(
            model_name='jobsource',
            name='ats',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('workday', 'Workday')], default='greenhouse', max_length=32),
        ),
    ]
